/**
 * CRUD write-feature manifest generator (RBAC-driven UI read-only).
 *
 * The admin UI hides an entity's edit/create/delete affordances when the viewer
 * lacks the write feature its CRUD mutation API requires. The mapping
 * (`entity id -> write features`) is declared implicitly by each route's
 * `makeCrudRoute` call, which registers it in a process-scoped registry at route
 * import time. That registry is only as complete as the set of routes loaded so
 * far, so a request-time resolution can be non-deterministic under Next.js's
 * lazy server bundles.
 *
 * This module renders that registry into a deterministic generated artifact
 * (`crud-write-features.generated.ts`) which bootstrap seeds into the registry
 * up front (`seedCrudWriteFeatureRegistry`), making resolution complete and
 * stable regardless of import order.
 *
 * The registry snapshot itself is captured by the OpenAPI generator's
 * module-execution pass — it already bundles and runs every route module, which
 * populates the registry as a byproduct — so we do not add a second full route
 * bundle. This module owns only the artifact's shape and write logic; the
 * OpenAPI generator hands it the captured snapshot.
 */

import * as path from 'node:path'
import type { PackageResolver } from '../resolver'
import {
  writeGeneratedFile,
  type GeneratorResult,
  createGeneratorResult,
} from '../utils'

/** Snapshot of the entity id (`module:entity`) → write-feature ids map. */
export type CrudWriteFeatureManifest = Record<string, readonly string[]>

export const CRUD_WRITE_FEATURES_OUTPUT_FILENAME = 'crud-write-features.generated.ts'
export const CRUD_WRITE_FEATURES_CHECKSUM_FILENAME = 'crud-write-features.generated.checksum'

/** Normalize the manifest into a deterministic, sorted, deduped shape. */
function normalizeManifest(registry: CrudWriteFeatureManifest | null | undefined): Record<string, string[]> {
  const out: Record<string, string[]> = {}
  if (!registry || typeof registry !== 'object') return out
  for (const entityId of Object.keys(registry).sort()) {
    const raw = registry[entityId]
    if (!Array.isArray(raw)) continue
    const features = Array.from(
      new Set(
        raw
          .filter((f): f is string => typeof f === 'string')
          .map((f) => f.trim())
          .filter(Boolean),
      ),
    ).sort()
    if (features.length) out[entityId] = features
  }
  return out
}

/** Render the generated TypeScript module for the manifest. */
export function renderCrudWriteFeaturesModule(
  registry: CrudWriteFeatureManifest | null | undefined,
): string {
  const manifest = normalizeManifest(registry)
  const entries = Object.entries(manifest)
  const body = entries.length
    ? entries
        .map(([entityId, features]) => `  ${JSON.stringify(entityId)}: [${features.map((f) => JSON.stringify(f)).join(', ')}],`)
        .join('\n')
    : ''
  return `// AUTO-GENERATED by \`mercato generate\` — do not edit.
//
// Maps each CRUD entity id to the write feature(s) its mutation API requires,
// captured by executing every route module at generate time. Seeded into the
// process registry at bootstrap so RBAC-driven UI read-only resolves
// deterministically, independent of which routes have been imported.
export const crudWriteFeatures: Record<string, string[]> = {${body ? `\n${body}\n` : ''}}
`
}

/**
 * Write the manifest artifact. `registry` is the snapshot captured by the
 * OpenAPI generator's route-execution pass (or `null`/empty when that pass was
 * skipped/failed — in which case an empty manifest is written so bootstrap can
 * always import it; the lazy `makeCrudRoute` registrations remain the backstop).
 */
export function writeCrudWriteFeaturesManifest(options: {
  resolver: PackageResolver
  registry: CrudWriteFeatureManifest | null | undefined
  quiet?: boolean
  result?: GeneratorResult
}): GeneratorResult {
  const { resolver, registry, quiet = false } = options
  const result = options.result ?? createGeneratorResult()

  const outputDir = resolver.getOutputDir()
  const outFile = path.join(outputDir, CRUD_WRITE_FEATURES_OUTPUT_FILENAME)
  const checksumFile = path.join(outputDir, CRUD_WRITE_FEATURES_CHECKSUM_FILENAME)

  const content = renderCrudWriteFeaturesModule(registry)
  // The manifest has no external source-tree inputs of its own (it rides on the
  // OpenAPI pass), so a content hash alone determines whether a rewrite is
  // needed — leave the structure checksum empty, as the OpenAPI generator does.
  writeGeneratedFile({ outFile, checksumFile, content, structureChecksum: '', result, quiet })
  return result
}
