import { z } from 'zod'
import { buildOpenApiDocument } from '../generator'
import type { Module, ModuleApiRouteFile } from '@open-mercato/shared/modules/registry'

type ResponseEntry = {
  description?: string
  'x-autoGenerated'?: boolean
}

function routeModule(route: ModuleApiRouteFile): Module {
  return {
    id: 'testing',
    apis: [route],
  } as unknown as Module
}

function getResponse(mod: Module, path: string, status: string): ResponseEntry {
  const doc = buildOpenApiDocument([mod])
  const operation = (doc.paths[path] as Record<string, { responses: Record<string, ResponseEntry> }>).get
  return operation.responses[status]
}

const noopHandler = (() => new Response(null)) as unknown as ModuleApiRouteFile['handlers']['GET']

describe('buildResponses precedence', () => {
  it('keeps a route-declared 403 (via responses) over the metadata-inferred one', () => {
    const mod = routeModule({
      path: '/api/things',
      handlers: { GET: noopHandler },
      metadata: { GET: { requireAuth: true, requireFeatures: ['things.view'] } },
      docs: {
        methods: {
          GET: {
            responses: [
              { status: 200, description: 'OK', schema: z.object({ ok: z.boolean() }) },
              { status: 403, description: 'Account is inactive', schema: z.object({ error: z.string() }) },
            ],
          },
        },
      },
    })

    const forbidden = getResponse(mod, '/api/things', '403')
    expect(forbidden.description).toBe('Account is inactive')
    expect(forbidden['x-autoGenerated']).toBeUndefined()
  })

  it('keeps a route-declared 403 (via errors) over the metadata-inferred one', () => {
    const mod = routeModule({
      path: '/api/things',
      handlers: { GET: noopHandler },
      metadata: { GET: { requireFeatures: ['things.view'] } },
      docs: {
        methods: {
          GET: {
            responses: [{ status: 200, description: 'OK', schema: z.object({ ok: z.boolean() }) }],
            errors: [{ status: 403, description: 'Account is inactive', schema: z.object({ error: z.string() }) }],
          },
        },
      },
    })

    const forbidden = getResponse(mod, '/api/things', '403')
    expect(forbidden.description).toBe('Account is inactive')
    expect(forbidden['x-autoGenerated']).toBeUndefined()
  })

  it('keeps a route-declared 401 over the metadata-inferred one', () => {
    const mod = routeModule({
      path: '/api/things',
      handlers: { GET: noopHandler },
      metadata: { GET: { requireAuth: true } },
      docs: {
        methods: {
          GET: {
            responses: [
              { status: 200, description: 'OK', schema: z.object({ ok: z.boolean() }) },
              { status: 401, description: 'Session token expired', schema: z.object({ error: z.string() }) },
            ],
          },
        },
      },
    })

    const unauthorized = getResponse(mod, '/api/things', '401')
    expect(unauthorized.description).toBe('Session token expired')
    expect(unauthorized['x-autoGenerated']).toBeUndefined()
  })

  it('still synthesises the metadata-inferred 401/403 when the route declares neither', () => {
    const mod = routeModule({
      path: '/api/things',
      handlers: { GET: noopHandler },
      metadata: { GET: { requireAuth: true, requireFeatures: ['things.view'] } },
      docs: {
        methods: {
          GET: {
            responses: [{ status: 200, description: 'OK', schema: z.object({ ok: z.boolean() }) }],
          },
        },
      },
    })

    const unauthorized = getResponse(mod, '/api/things', '401')
    expect(unauthorized.description).toBe('Unauthorized')
    expect(unauthorized['x-autoGenerated']).toBe(true)

    const forbidden = getResponse(mod, '/api/things', '403')
    expect(forbidden.description).toBe('Forbidden – missing required features')
    expect(forbidden['x-autoGenerated']).toBe(true)
  })
})
